spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/mosaic

logging:
  level:
    org:
      springframework:
        security: TRACE

